# Generated by Django 4.0.6 on 2022-08-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
