# Generated by Django 4.0.6 on 2022-08-10 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import videoclips.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование')),
                ('icon', models.CharField(choices=[('HRT', 'Лайк'), ('FG', 'Большой палец'), ('SM', 'Улыбка')], max_length=40, verbose_name='Иконка')),
            ],
        ),
        migrations.CreateModel(
            name='VCCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclips.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Videoclip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('upload', models.FileField(upload_to=videoclips.models.user_directory_path)),
                ('create_date', models.DateTimeField(verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('categories', models.ManyToManyField(through='videoclips.VCCategory', to='videoclips.category', verbose_name='Категории')),
            ],
        ),
        migrations.CreateModel(
            name='VCSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='Дата')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclips.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='VCReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclips.reaction', verbose_name='Реакция')),
                ('videoclip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclips.videoclip', verbose_name='Видео')),
            ],
        ),
        migrations.CreateModel(
            name='VCComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='Дата')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('videoclip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclips.videoclip', verbose_name='Видео')),
            ],
        ),
        migrations.AddField(
            model_name='vccategory',
            name='videoclip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclips.videoclip', verbose_name='Видео'),
        ),
        migrations.CreateModel(
            name='VCBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_date', models.DateTimeField(verbose_name='Бан до')),
                ('create_date', models.DateTimeField(verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('videoclip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclips.videoclip', verbose_name='Видео')),
            ],
        ),
        migrations.CreateModel(
            name='UserReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='Дата')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclips.reaction', verbose_name='Реакция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('videoclip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclips.videoclip', verbose_name='Видео')),
            ],
        ),
    ]
