# Generated by Django 4.0.6 on 2022-08-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoclip',
            name='name',
        ),
        migrations.AddField(
            model_name='videoclip',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
