# Generated by Django 4.0.6 on 2022-08-21 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import videoclips.models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclips', '0002_remove_videoclip_name_videoclip_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vcban',
            old_name='user',
            new_name='baned_user',
        ),
        migrations.AlterField(
            model_name='vcban',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='vccomment',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='vcreaction',
            name='videoclip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='videoclips.videoclip', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='upload',
            field=models.FileField(blank=True, upload_to=videoclips.models.user_directory_path),
        ),
    ]
