# Generated by Django 4.0.6 on 2022-08-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoclips', '0003_rename_user_vcban_baned_user_alter_vcban_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vcban',
            old_name='baned_user',
            new_name='banned_user',
        ),
    ]
