# Generated by Django 4.0.6 on 2022-08-21 20:37

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoclips', '0005_alter_vcban_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaction',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterUniqueTogether(
            name='userreaction',
            unique_together={('videoclip', 'user', 'reaction')},
        ),
    ]
