# Generated by Django 4.0.6 on 2022-08-21 21:28

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoclips', '0006_alter_userreaction_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcsubscription',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterUniqueTogether(
            name='vcsubscription',
            unique_together={('user', 'category')},
        ),
    ]
